// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgwATQfnRpGb9qp7eo5XKwlsUQJr2BZzM',
    appId: '1:119076477805:web:8756e1265552e7fc409864',
    messagingSenderId: '119076477805',
    projectId: 'aloroupia',
    authDomain: 'aloroupia.firebaseapp.com',
    storageBucket: 'aloroupia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaAanSypPUwBeRyQLjwH8iBEn4B1P01M8',
    appId: '1:119076477805:android:b45e2375d2617a7c409864',
    messagingSenderId: '119076477805',
    projectId: 'aloroupia',
    storageBucket: 'aloroupia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY2DYSSh9XSlX93MA_mTfjAbQ8KHzFebs',
    appId: '1:119076477805:ios:293852cf52f98d90409864',
    messagingSenderId: '119076477805',
    projectId: 'aloroupia',
    storageBucket: 'aloroupia.firebasestorage.app',
    iosBundleId: 'com.example.aloroupia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY2DYSSh9XSlX93MA_mTfjAbQ8KHzFebs',
    appId: '1:119076477805:ios:293852cf52f98d90409864',
    messagingSenderId: '119076477805',
    projectId: 'aloroupia',
    storageBucket: 'aloroupia.firebasestorage.app',
    iosBundleId: 'com.example.aloroupia',
  );
}
